[strategy]
spread = 200
currency_pair = { base = "eth", quote = "usdt" }
max_amount = 0.02
exchange_account_id = "Binance_0"

[[core.exchanges]]
exchange_account_id = "Binance_0"
is_margin_trading = false
request_trades = false
websocket_channels = ["depth20@100ms"]
subscribe_to_market_data = true

currency_pairs = [
    { base = "eth", quote = "usdt"  },
    # { base = "eos", quote = "btc"  },
    # { base = "btc", quote = "usdt" },
    # { base = "bnb", quote = "usdt" },
]
